server:
  port: 8080

spring:
  application:
    name: CrediYaAuth
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crediya_auth}
    username: ${DB_USERNAME:crediya_user}
    password: ${DB_PASSWORD:crediya_pass}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: http://localhost:4200,http://localhost:8080

routes:
  paths:
    users: /api/v1/users
